/**
 * Data factory — generates realistic Belgian property management data.
 * Used by both the E2E minimal seed and the dev seed script.
 */

// ─── Buildings ────────────────────────────────────────────────────────────────

export const BUILDINGS = [
  {
    name: "Résidence Les Tilleuls",
    streetAddress: "Rue de la Loi 42",
    postalCode: "1000",
    city: "Bruxelles",
    unitCount: 5,
  },
  {
    name: "Immeuble du Parc",
    streetAddress: "Avenue du Parc 18",
    postalCode: "4000",
    city: "Liège",
    unitCount: 4,
  },
  {
    name: "Résidence Gaston",
    streetAddress: "Veldstraat 77",
    postalCode: "9000",
    city: "Gent",
    unitCount: 3,
  },
  {
    name: "Le Beffroi",
    streetAddress: "Grand-Place 5",
    postalCode: "7000",
    city: "Mons",
    unitCount: 2,
  },
  {
    name: "Résidence Meuse",
    streetAddress: "Quai de Namur 12",
    postalCode: "5000",
    city: "Namur",
    unitCount: 4,
  },
];

// ─── Unit templates per building ──────────────────────────────────────────────

export function generateUnits(buildingIndex: number): Array<{
  unitNumber: string;
  floor: number;
  totalSurface: number;
  hasTerrace: boolean;
  terraceSurface?: number;
  terraceOrientation?: string;
  hasGarden: boolean;
  gardenSurface?: number;
  gardenOrientation?: string;
}> {
  const templates = [
    [
      {
        unitNumber: "A01",
        floor: 0,
        totalSurface: 75,
        hasTerrace: false,
        hasGarden: true,
        gardenSurface: 30,
        gardenOrientation: "S",
      },
      {
        unitNumber: "A02",
        floor: 0,
        totalSurface: 68,
        hasTerrace: false,
        hasGarden: false,
      },
      {
        unitNumber: "B01",
        floor: 1,
        totalSurface: 82,
        hasTerrace: true,
        terraceSurface: 12,
        terraceOrientation: "SW",
        hasGarden: false,
      },
      {
        unitNumber: "B02",
        floor: 1,
        totalSurface: 79,
        hasTerrace: true,
        terraceSurface: 10,
        terraceOrientation: "NE",
        hasGarden: false,
      },
      {
        unitNumber: "C01",
        floor: 2,
        totalSurface: 91,
        hasTerrace: true,
        terraceSurface: 15,
        terraceOrientation: "S",
        hasGarden: false,
      },
    ],
    [
      {
        unitNumber: "01",
        floor: 0,
        totalSurface: 65,
        hasTerrace: false,
        hasGarden: true,
        gardenSurface: 25,
        gardenOrientation: "SW",
      },
      {
        unitNumber: "02",
        floor: 0,
        totalSurface: 58,
        hasTerrace: false,
        hasGarden: false,
      },
      {
        unitNumber: "11",
        floor: 1,
        totalSurface: 72,
        hasTerrace: true,
        terraceSurface: 8,
        terraceOrientation: "S",
        hasGarden: false,
      },
      {
        unitNumber: "12",
        floor: 1,
        totalSurface: 69,
        hasTerrace: false,
        hasGarden: false,
      },
    ],
    [
      {
        unitNumber: "RDC",
        floor: 0,
        totalSurface: 88,
        hasTerrace: false,
        hasGarden: true,
        gardenSurface: 40,
        gardenOrientation: "S",
      },
      {
        unitNumber: "1er",
        floor: 1,
        totalSurface: 76,
        hasTerrace: true,
        terraceSurface: 10,
        terraceOrientation: "W",
        hasGarden: false,
      },
      {
        unitNumber: "2ème",
        floor: 2,
        totalSurface: 83,
        hasTerrace: true,
        terraceSurface: 14,
        terraceOrientation: "SW",
        hasGarden: false,
      },
    ],
    [
      {
        unitNumber: "A",
        floor: 0,
        totalSurface: 62,
        hasTerrace: false,
        hasGarden: false,
      },
      {
        unitNumber: "B",
        floor: 1,
        totalSurface: 71,
        hasTerrace: true,
        terraceSurface: 9,
        terraceOrientation: "SE",
        hasGarden: false,
      },
    ],
    [
      {
        unitNumber: "T1",
        floor: 0,
        totalSurface: 67,
        hasTerrace: false,
        hasGarden: true,
        gardenSurface: 20,
        gardenOrientation: "E",
      },
      {
        unitNumber: "T2",
        floor: 0,
        totalSurface: 71,
        hasTerrace: false,
        hasGarden: false,
      },
      {
        unitNumber: "T3",
        floor: 1,
        totalSurface: 78,
        hasTerrace: true,
        terraceSurface: 11,
        terraceOrientation: "S",
        hasGarden: false,
      },
      {
        unitNumber: "T4",
        floor: 1,
        totalSurface: 74,
        hasTerrace: false,
        hasGarden: false,
      },
    ],
  ];
  return templates[buildingIndex] ?? templates[0];
}

// ─── Rooms ────────────────────────────────────────────────────────────────────

export function generateRooms(totalSurface: number) {
  const rooms = [
    {
      roomType: "LIVING_ROOM",
      approximateSurface: Math.round(totalSurface * 0.3),
    },
    { roomType: "BEDROOM", approximateSurface: Math.round(totalSurface * 0.2) },
    {
      roomType: "KITCHEN",
      approximateSurface: Math.round(totalSurface * 0.15),
    },
    {
      roomType: "BATHROOM",
      approximateSurface: Math.round(totalSurface * 0.1),
    },
  ];
  if (totalSurface >= 80) {
    rooms.push({
      roomType: "BEDROOM",
      approximateSurface: Math.round(totalSurface * 0.18),
    });
  }
  return rooms;
}

// ─── Persons ──────────────────────────────────────────────────────────────────

export const PERSONS = [
  // owners (0–4)
  {
    firstName: "Alexandre",
    lastName: "Dubois",
    email: "a.dubois@gmail.com",
    gsm: "+32 476 12 34 56",
    city: "Bruxelles",
    postalCode: "1000",
    streetAddress: "Avenue Louise 120",
    nationalId: "BE-001",
  },
  {
    firstName: "Isabelle",
    lastName: "Maes",
    email: "i.maes@skynet.be",
    gsm: "+32 477 23 45 67",
    city: "Liège",
    postalCode: "4000",
    streetAddress: "Rue de la Paix 7",
    nationalId: "BE-002",
  },
  {
    firstName: "Pieter",
    lastName: "Vermeersch",
    email: "p.vermeersch@telenet.be",
    gsm: "+32 478 34 56 78",
    city: "Gent",
    postalCode: "9000",
    streetAddress: "Korenmarkt 3",
    nationalId: "BE-003",
  },
  {
    firstName: "Claire",
    lastName: "Lejeune",
    email: "c.lejeune@hotmail.com",
    gsm: "+32 479 45 67 89",
    city: "Mons",
    postalCode: "7000",
    streetAddress: "Rue de la Grande Triperie 14",
    nationalId: "BE-004",
  },
  {
    firstName: "Marc",
    lastName: "Collignon",
    email: "m.collignon@outlook.be",
    gsm: "+32 495 56 78 90",
    city: "Namur",
    postalCode: "5000",
    streetAddress: "Rue du Collège 8",
    nationalId: "BE-005",
  },
  // tenants (5–19)
  {
    firstName: "Martin",
    lastName: "Lecomte",
    email: "m.lecomte@gmail.com",
    gsm: "+32 486 01 23 45",
    city: "Bruxelles",
    postalCode: "1050",
    streetAddress: "Chaussée d'Ixelles 34",
    nationalId: "BE-006",
  },
  {
    firstName: "Sophie",
    lastName: "Renard",
    email: "s.renard@yahoo.fr",
    gsm: "+32 487 12 34 56",
    city: "Liège",
    postalCode: "4020",
    streetAddress: "Boulevard de la Constitution 21",
    nationalId: "BE-007",
  },
  {
    firstName: "Thomas",
    lastName: "Van den Berg",
    email: "t.vandenberg@gmail.com",
    gsm: "+32 488 23 45 67",
    city: "Gent",
    postalCode: "9000",
    streetAddress: "Brabantdam 28",
    nationalId: "BE-008",
  },
  {
    firstName: "Laura",
    lastName: "Peeters",
    email: "l.peeters@telenet.be",
    gsm: "+32 489 34 56 78",
    city: "Bruxelles",
    postalCode: "1180",
    streetAddress: "Avenue Winston Churchill 45",
    nationalId: "BE-009",
  },
  {
    firstName: "Antoine",
    lastName: "Bodart",
    email: "a.bodart@gmail.com",
    gsm: "+32 490 45 67 89",
    city: "Namur",
    postalCode: "5000",
    streetAddress: "Rue des Brasseurs 19",
    nationalId: "BE-010",
  },
  {
    firstName: "Emma",
    lastName: "Claes",
    email: "e.claes@hotmail.be",
    gsm: "+32 491 56 78 90",
    city: "Gent",
    postalCode: "9040",
    streetAddress: "Wiedauwkaai 12",
    nationalId: "BE-011",
  },
  {
    firstName: "Lucas",
    lastName: "Pirard",
    email: "l.pirard@gmail.com",
    gsm: "+32 492 67 89 01",
    city: "Liège",
    postalCode: "4000",
    streetAddress: "Rue Saint-Gilles 55",
    nationalId: "BE-012",
  },
  {
    firstName: "Céline",
    lastName: "Willems",
    email: "c.willems@skynet.be",
    gsm: "+32 493 78 90 12",
    city: "Mons",
    postalCode: "7000",
    streetAddress: "Rue des Arbalestriers 8",
    nationalId: "BE-013",
  },
  {
    firstName: "Julien",
    lastName: "De Smedt",
    email: "j.desmedt@gmail.com",
    gsm: "+32 494 89 01 23",
    city: "Gent",
    postalCode: "9000",
    streetAddress: "Brabantdam 28",
    nationalId: "BE-014",
  },
  {
    firstName: "Nicolas",
    lastName: "Jacobs",
    email: "n.jacobs@telenet.be",
    gsm: "+32 471 00 11 22",
    city: "Bruxelles",
    postalCode: "1180",
    streetAddress: "Avenue Molière 67",
    nationalId: "BE-015",
  },
  {
    firstName: "Isabelle",
    lastName: "Fontaine",
    email: "i.fontaine@gmail.com",
    gsm: "+32 472 11 22 33",
    city: "Namur",
    postalCode: "5100",
    streetAddress: "Rue du Collège 12",
    nationalId: "BE-016",
  },
  {
    firstName: "Kevin",
    lastName: "Mertens",
    email: "k.mertens@outlook.be",
    gsm: "+32 473 22 33 44",
    city: "Mons",
    postalCode: "7000",
    streetAddress: "Avenue de Valenciennes 4",
    nationalId: "BE-017",
  },
  {
    firstName: "Sarah",
    lastName: "Baert",
    email: "s.baert@hotmail.com",
    gsm: "+32 474 33 44 55",
    city: "Gent",
    postalCode: "9000",
    streetAddress: "Coupure Links 82",
    nationalId: "BE-018",
  },
  {
    firstName: "Romain",
    lastName: "Henry",
    email: "r.henry@gmail.com",
    gsm: "+32 475 44 55 66",
    city: "Bruxelles",
    postalCode: "1000",
    streetAddress: "Boulevard du Midi 33",
    nationalId: "BE-019",
  },
  {
    firstName: "Nathalie",
    lastName: "Dumont",
    email: "n.dumont@skynet.be",
    gsm: "+32 476 55 66 77",
    city: "Liège",
    postalCode: "4000",
    streetAddress: "Rue Hors-Château 19",
    nationalId: "BE-020",
  },
];

// ─── Lease scenarios ──────────────────────────────────────────────────────────

export type LeaseScenario =
  | "active"
  | "active-with-adjustments"
  | "finished"
  | "finished-with-adjustments"
  | "draft"
  | "cancelled";

export interface LeaseTemplate {
  scenario: LeaseScenario;
  leaseType: string;
  durationMonths: number;
  noticePeriodMonths: number;
  baseRent: number;
  charges: number;
  chargesType: string;
  depositMultiplier: number;
  yearsAgo: number;
}

export const LEASE_TEMPLATES: LeaseTemplate[] = [
  {
    scenario: "active",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 850,
    charges: 80,
    chargesType: "FORFAIT",
    depositMultiplier: 2,
    yearsAgo: 2,
  },
  {
    scenario: "active",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 720,
    charges: 60,
    chargesType: "FORFAIT",
    depositMultiplier: 2,
    yearsAgo: 1,
  },
  {
    scenario: "active-with-adjustments",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 950,
    charges: 100,
    chargesType: "PROVISION",
    depositMultiplier: 2,
    yearsAgo: 3,
  },
  {
    scenario: "active",
    leaseType: "SHORT_TERM",
    durationMonths: 36,
    noticePeriodMonths: 1,
    baseRent: 680,
    charges: 50,
    chargesType: "FORFAIT",
    depositMultiplier: 2,
    yearsAgo: 1,
  },
  {
    scenario: "active-with-adjustments",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 1050,
    charges: 120,
    chargesType: "PROVISION",
    depositMultiplier: 3,
    yearsAgo: 4,
  },
  {
    scenario: "finished",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 780,
    charges: 70,
    chargesType: "FORFAIT",
    depositMultiplier: 2,
    yearsAgo: 5,
  },
  {
    scenario: "finished-with-adjustments",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 820,
    charges: 85,
    chargesType: "FORFAIT",
    depositMultiplier: 2,
    yearsAgo: 6,
  },
  {
    scenario: "draft",
    leaseType: "MAIN_RESIDENCE_9Y",
    durationMonths: 108,
    noticePeriodMonths: 3,
    baseRent: 890,
    charges: 90,
    chargesType: "PROVISION",
    depositMultiplier: 2,
    yearsAgo: 0,
  },
  {
    scenario: "cancelled",
    leaseType: "SHORT_TERM",
    durationMonths: 12,
    noticePeriodMonths: 1,
    baseRent: 650,
    charges: 55,
    chargesType: "FORFAIT",
    depositMultiplier: 1,
    yearsAgo: 1,
  },
];

export const RENT_ADJUSTMENT_REASONS = [
  "Indexation annuelle loyer (art. 1728bis C.civ.)",
  "Accord parties — révision loyer",
  "Indexation indice santé",
  "Révision triennale — accord amiable",
];

// ─── Meter templates ──────────────────────────────────────────────────────────

export function generateUnitMeters(unitId: number, unitIndex: number) {
  const base = (unitId * 1000 + unitIndex).toString().padStart(8, "0");
  const meters = [
    {
      type: "ELECTRICITY",
      meterNumber: `EL${base}`,
      label: "Main electricity",
      eanCode: `541445900${base.slice(0, 9)}`,
      startDate: "2018-01-01",
    },
  ];
  if (unitIndex % 2 === 0) {
    meters.push({
      type: "GAS",
      meterNumber: `GZ${base}`,
      label: "Natural gas",
      eanCode: `541234500${base.slice(0, 9)}`,
      startDate: "2018-01-01",
    });
  }
  return meters;
}

export function generateBuildingMeters(buildingId: number) {
  const base = (buildingId * 100).toString().padStart(6, "0");
  return [
    {
      type: "WATER",
      meterNumber: `WA${base}`,
      label: "Common areas water",
      installationNumber: `INS${base}`,
      customerNumber: `CUS${base}`,
      startDate: "2015-06-01",
    },
  ];
}

// ─── Boiler templates ─────────────────────────────────────────────────────────

export const BOILER_BRANDS = [
  { brand: "Vaillant", model: "ecoTEC Plus", fuelType: "GAS" },
  { brand: "Buderus", model: "Logamax U072", fuelType: "GAS" },
  { brand: "Viessmann", model: "Vitodens 100-W", fuelType: "GAS" },
  { brand: "Daikin", model: "Altherma 3", fuelType: "HEAT_PUMP" },
  { brand: "Saunier Duval", model: "ThemaFast", fuelType: "GAS" },
];

export function generateBoiler(index: number, installYear: number) {
  const brand = BOILER_BRANDS[index % BOILER_BRANDS.length];
  const installDate = `${installYear}-03-15`;
  const lastService = `${installYear + 2}-03-15`;
  const nextService = `${installYear + 3}-03-15`;
  return {
    ...brand,
    installationDate: installDate,
    lastServiceDate: lastService,
    nextServiceDate: nextService,
    serialNumber: `SN-${(index + 1) * 1234567}`,
  };
}

// ─── Date helpers ─────────────────────────────────────────────────────────────

export function isoDate(date: Date): string {
  return date.toISOString().split("T")[0];
}

export function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

export function yearsAgo(years: number): Date {
  const d = new Date();
  d.setFullYear(d.getFullYear() - years);
  d.setDate(1);
  return d;
}

// ─── Bank accounts seed ───────────────────────────────────────────────────────

export const BANK_ACCOUNTS_SEED = [
  {
    label: "ING Compte courant",
    accountNumber: "BE56310126914878",
    type: "CURRENT" as const,
    isActive: true,
  },
  {
    label: "Belfius Épargne",
    accountNumber: "BE71068897594776",
    type: "SAVINGS" as const,
    isActive: true,
  },
  {
    label: "BNP Paribas Fortis",
    accountNumber: "BE43001599922670",
    type: "CURRENT" as const,
    isActive: true,
  },
];

// ─── Transaction counterparties ───────────────────────────────────────────────

export const COUNTERPARTIES = {
  swde: { name: "SWDE", iban: "BE43068900527891" },
  vivaqua: { name: "Vivaqua", iban: "BE19210010518006" },
  farys: { name: "Farys", iban: "BE41091000123456" },
  engie: { name: "Engie", iban: "BE55877055007500" },
  luminus: { name: "Luminus", iban: "BE96000000264586" },
  ores: { name: "Ores", iban: "BE65001610440006" },
  cleanPro: { name: "CleanPro SPRL", iban: "BE29360186856303" },
  sparkle: { name: "Sparkle Nettoyage", iban: "BE71310112345678" },
  securitas: { name: "Securitas Fire Services", iban: "BE88363130805117" },
  safefire: { name: "SafeFire Belgium", iban: "BE45001234567890" },
  technikabel: { name: "Technikabel SPRL", iban: "BE32360186856310" },
  climaService: { name: "ClimaService SA", iban: "BE74001199203993" },
  vaillantTech: { name: "Vaillant Service", iban: "BE61001789456123" },
  plomberieDupont: { name: "Plomberie Dupont", iban: "BE29001900654321" },
  waterfixBxl: { name: "WaterFix Bruxelles", iban: "BE41360098761234" },
  renovImmo: { name: "Renov'Immo SA", iban: "BE67001155443322" },
  toitureWaals: { name: "Toiture Waals & Fils", iban: "BE83363005556677" },
  batiTravaux: { name: "BatiTravaux SPRL", iban: "BE24001700112233" },
  agInsurance: { name: "AG Insurance", iban: "BE71545600000000" },
  axa: { name: "AXA Belgium", iban: "BE97001200094353" },
  spfFinances: { name: "SPF Finances", iban: "BE86601001680060" },
  communeBxl: { name: "Commune de Bruxelles", iban: "BE61091000012345" },
  renteNotaire: { name: "Étude Notariale Mercier", iban: "BE53001300987654" },
  usufructier1: { name: "Marie-Claire Vandenbroeck", iban: "BE41001400123456" },
  usufructier2: { name: "Paul Goffin", iban: "BE29363011223344" },
  ing: { name: "ING Belgique", iban: "BE56310126914878" },
  belfius: { name: "Belfius Banque", iban: "BE71068897594776" },
  immotoolsSub: { name: "ImmoTools SaaS", iban: "BE65001700556677" },
  syndic: { name: "Syndic Gestion Urbaine", iban: "BE83001900778899" },
  leroy: { name: "Leroy Merlin", iban: undefined },
  brico: { name: "Brico", iban: undefined },
  ikea: { name: "IKEA Belgium", iban: undefined },
  elecBxl: { name: "Électricité Bruxelles SPRL", iban: "BE41001600334455" },
  vitrage: { name: "Vitrages & Co", iban: "BE29001500223344" },
  locksmith: { name: "Serrurerie Rapide", iban: undefined },
};

// ─── Rent transaction generator ───────────────────────────────────────────────
// Generates one INCOME transaction per occupied month for a given lease.

export interface RentTransactionParams {
  tenantName: string;
  tenantIban: string;
  monthlyRent: number;
  monthlyCharges: number;
  leaseStartDate: Date;
  /** use lease end date or today, whichever is earlier */
  leaseEndDate: Date;
  buildingIndex: number;
  unitIndex: number;
}

export function generateRentTransactions(p: RentTransactionParams): Array<{
  direction: "INCOME";
  subcategoryName: "Loyer";
  transactionDate: string;
  accountingMonth: string;
  amount: number;
  description: string;
  counterpartyAccount: string;
  buildingIndex: number;
  unitIndex: number;
}> {
  const result = [];
  const ceiling = p.leaseEndDate < new Date() ? p.leaseEndDate : new Date();

  const cursor = new Date(p.leaseStartDate);
  cursor.setDate(5); // paid on the 5th

  while (cursor <= ceiling) {
    const first = new Date(cursor);
    first.setDate(1);
    const dateStr = isoDate(cursor);
    const monthStr = isoDate(first);
    const label = cursor.toLocaleString("fr-BE", {
      month: "long",
      year: "numeric",
    });
    result.push({
      direction: "INCOME" as const,
      subcategoryName: "Loyer" as const,
      transactionDate: dateStr,
      accountingMonth: monthStr,
      amount: p.monthlyRent + p.monthlyCharges,
      description: `Loyer + charges ${label}`,
      counterpartyName: p.tenantName,
      counterpartyAccount: p.tenantIban,
      buildingIndex: p.buildingIndex,
      unitIndex: p.unitIndex,
    });
    cursor.setMonth(cursor.getMonth() + 1);
  }
  return result;
}

// ─── Punctual / semi-recurring transactions ───────────────────────────────────
// ~200 transactions spanning 2023-01-01 to 2025-12-31.
// Categories used (as seeded in V013):
//   Eau, Electricité, Gaz, Chaudière, Extincteurs, Nettoyage communs,
//   Usufruit, Retour, Précompte immobilier, Assurance habitation,
//   Plomberie, Structure, Toiture, Petits travaux, Annonce,
//   Etat des lieux, Garantie locative, Petits frais, Adoucisseur, Banque

export interface PunctualTransaction {
  direction: "INCOME" | "EXPENSE";
  subcategoryName: string;
  transactionDate: string;
  accountingMonth: string;
  amount: number;
  description: string;
  counterpartyName: string;
  counterpartyAccount?: string;
  buildingIndex?: number;
  unitIndex?: number;
}

export const PUNCTUAL_TRANSACTIONS: PunctualTransaction[] = [
  // ── Water — SWDE (Liège, quarterly) ───────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-01-20",
    accountingMonth: "2023-01-01",
    amount: 187.4,
    description: "Facture eau Q4 2022 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-04-18",
    accountingMonth: "2023-04-01",
    amount: 201.6,
    description: "Facture eau Q1 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-07-21",
    accountingMonth: "2023-07-01",
    amount: 194.2,
    description: "Facture eau Q2 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-10-17",
    accountingMonth: "2023-10-01",
    amount: 209.8,
    description: "Facture eau Q3 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-01-22",
    accountingMonth: "2024-01-01",
    amount: 198.5,
    description: "Facture eau Q4 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-04-19",
    accountingMonth: "2024-04-01",
    amount: 211.3,
    description: "Facture eau Q1 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-07-18",
    accountingMonth: "2024-07-01",
    amount: 205.7,
    description: "Facture eau Q2 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-10-21",
    accountingMonth: "2024-10-01",
    amount: 218.9,
    description: "Facture eau Q3 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2025-01-20",
    accountingMonth: "2025-01-01",
    amount: 203.2,
    description: "Facture eau Q4 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2025-04-17",
    accountingMonth: "2025-04-01",
    amount: 214.6,
    description: "Facture eau Q1 2025 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.swde.name,
    counterpartyAccount: COUNTERPARTIES.swde.iban,
    buildingIndex: 1,
  },

  // ── Water — Vivaqua (Bruxelles, bimonthly) ────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-02-14",
    accountingMonth: "2023-02-01",
    amount: 312.5,
    description: "Facture eau bim. jan-fév 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-04-13",
    accountingMonth: "2023-04-01",
    amount: 298.8,
    description: "Facture eau bim. mar-avr 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-06-15",
    accountingMonth: "2023-06-01",
    amount: 324.1,
    description: "Facture eau bim. mai-jun 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-08-14",
    accountingMonth: "2023-08-01",
    amount: 341.6,
    description: "Facture eau bim. jul-aoû 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-10-16",
    accountingMonth: "2023-10-01",
    amount: 307.9,
    description: "Facture eau bim. sep-oct 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-12-14",
    accountingMonth: "2023-12-01",
    amount: 289.4,
    description: "Facture eau bim. nov-déc 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-02-13",
    accountingMonth: "2024-02-01",
    amount: 318.2,
    description: "Facture eau bim. jan-fév 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-04-15",
    accountingMonth: "2024-04-01",
    amount: 302.7,
    description: "Facture eau bim. mar-avr 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-06-14",
    accountingMonth: "2024-06-01",
    amount: 335.5,
    description: "Facture eau bim. mai-jun 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-08-13",
    accountingMonth: "2024-08-01",
    amount: 358.3,
    description: "Facture eau bim. jul-aoû 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-10-15",
    accountingMonth: "2024-10-01",
    amount: 321.8,
    description: "Facture eau bim. sep-oct 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-12-13",
    accountingMonth: "2024-12-01",
    amount: 295.6,
    description: "Facture eau bim. nov-déc 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2025-02-14",
    accountingMonth: "2025-02-01",
    amount: 309.4,
    description: "Facture eau bim. jan-fév 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vivaqua.name,
    counterpartyAccount: COUNTERPARTIES.vivaqua.iban,
    buildingIndex: 0,
  },

  // ── Water — Farys (Gent, quarterly) ──────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-03-10",
    accountingMonth: "2023-03-01",
    amount: 156.4,
    description: "Facture eau Q4 2022 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-06-09",
    accountingMonth: "2023-06-01",
    amount: 162.8,
    description: "Facture eau Q1 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-09-08",
    accountingMonth: "2023-09-01",
    amount: 171.2,
    description: "Facture eau Q2 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2023-12-07",
    accountingMonth: "2023-12-01",
    amount: 158.9,
    description: "Facture eau Q3 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-03-08",
    accountingMonth: "2024-03-01",
    amount: 167.5,
    description: "Facture eau Q4 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-06-07",
    accountingMonth: "2024-06-01",
    amount: 174.3,
    description: "Facture eau Q1 2024 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-09-06",
    accountingMonth: "2024-09-01",
    amount: 169.7,
    description: "Facture eau Q2 2024 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2024-12-06",
    accountingMonth: "2024-12-01",
    amount: 178.4,
    description: "Facture eau Q3 2024 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Eau",
    transactionDate: "2025-03-07",
    accountingMonth: "2025-03-01",
    amount: 163.2,
    description: "Facture eau Q4 2024 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.farys.name,
    counterpartyAccount: COUNTERPARTIES.farys.iban,
    buildingIndex: 2,
  },

  // ── Electricity — Engie (Bruxelles common areas) ──────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-01-28",
    accountingMonth: "2023-01-01",
    amount: 423.8,
    description: "Élec. parties communes jan 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-02-27",
    accountingMonth: "2023-02-01",
    amount: 398.5,
    description: "Élec. parties communes fév 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-03-29",
    accountingMonth: "2023-03-01",
    amount: 367.2,
    description: "Élec. parties communes mar 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-07-28",
    accountingMonth: "2023-07-01",
    amount: 289.6,
    description: "Élec. parties communes jul 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-10-30",
    accountingMonth: "2023-10-01",
    amount: 352.4,
    description: "Élec. parties communes oct 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2024-01-29",
    accountingMonth: "2024-01-01",
    amount: 441.7,
    description: "Élec. parties communes jan 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2024-04-29",
    accountingMonth: "2024-04-01",
    amount: 318.9,
    description: "Élec. parties communes avr 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2024-10-28",
    accountingMonth: "2024-10-01",
    amount: 376.3,
    description: "Élec. parties communes oct 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2025-01-28",
    accountingMonth: "2025-01-01",
    amount: 459.2,
    description: "Élec. parties communes jan 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },

  // ── Electricity — Luminus (Liège) ─────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-01-31",
    accountingMonth: "2023-01-01",
    amount: 234.6,
    description: "Élec. parties communes jan 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-04-28",
    accountingMonth: "2023-04-01",
    amount: 198.4,
    description: "Élec. parties communes avr 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2023-10-31",
    accountingMonth: "2023-10-01",
    amount: 221.8,
    description: "Élec. parties communes oct 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2024-01-30",
    accountingMonth: "2024-01-01",
    amount: 247.3,
    description: "Élec. parties communes jan 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2024-07-30",
    accountingMonth: "2024-07-01",
    amount: 189.5,
    description: "Élec. parties communes jul 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Electricité",
    transactionDate: "2025-01-30",
    accountingMonth: "2025-01-01",
    amount: 258.9,
    description: "Élec. parties communes jan 2025 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.luminus.name,
    counterpartyAccount: COUNTERPARTIES.luminus.iban,
    buildingIndex: 1,
  },

  // ── Gas — Engie (shared heating, winter months) ───────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-01-31",
    accountingMonth: "2023-01-01",
    amount: 1243.8,
    description: "Gaz chauffage collectif jan 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-02-28",
    accountingMonth: "2023-02-01",
    amount: 1189.4,
    description: "Gaz chauffage collectif fév 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-03-31",
    accountingMonth: "2023-03-01",
    amount: 987.6,
    description: "Gaz chauffage collectif mar 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-10-31",
    accountingMonth: "2023-10-01",
    amount: 876.3,
    description: "Gaz chauffage collectif oct 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-11-30",
    accountingMonth: "2023-11-01",
    amount: 1098.7,
    description: "Gaz chauffage collectif nov 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2023-12-31",
    accountingMonth: "2023-12-01",
    amount: 1312.5,
    description: "Gaz chauffage collectif déc 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2024-01-31",
    accountingMonth: "2024-01-01",
    amount: 1287.9,
    description: "Gaz chauffage collectif jan 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2024-02-29",
    accountingMonth: "2024-02-01",
    amount: 1156.4,
    description: "Gaz chauffage collectif fév 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2024-11-30",
    accountingMonth: "2024-11-01",
    amount: 1034.2,
    description: "Gaz chauffage collectif nov 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2024-12-31",
    accountingMonth: "2024-12-01",
    amount: 1378.6,
    description: "Gaz chauffage collectif déc 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2025-01-31",
    accountingMonth: "2025-01-01",
    amount: 1421.3,
    description: "Gaz chauffage collectif jan 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Gaz",
    transactionDate: "2025-02-28",
    accountingMonth: "2025-02-01",
    amount: 1198.7,
    description: "Gaz chauffage collectif fév 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.engie.name,
    counterpartyAccount: COUNTERPARTIES.engie.iban,
    buildingIndex: 0,
  },

  // ── Boiler maintenance ─────────────────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2023-03-15",
    accountingMonth: "2023-03-01",
    amount: 189.5,
    description: "Entretien annuel chaudière — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.technikabel.name,
    counterpartyAccount: COUNTERPARTIES.technikabel.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2023-04-20",
    accountingMonth: "2023-04-01",
    amount: 145.8,
    description: "Entretien chaudière unité A01 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.vaillantTech.name,
    counterpartyAccount: COUNTERPARTIES.vaillantTech.iban,
    buildingIndex: 0,
    unitIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2023-09-12",
    accountingMonth: "2023-09-01",
    amount: 267.4,
    description: "Remplacement vanne chaudière — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.climaService.name,
    counterpartyAccount: COUNTERPARTIES.climaService.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2024-03-14",
    accountingMonth: "2024-03-01",
    amount: 192.3,
    description: "Entretien annuel chaudière — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.technikabel.name,
    counterpartyAccount: COUNTERPARTIES.technikabel.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2024-04-11",
    accountingMonth: "2024-04-01",
    amount: 578.9,
    description: "Remplacement brûleur chaudière collective — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.climaService.name,
    counterpartyAccount: COUNTERPARTIES.climaService.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2024-09-18",
    accountingMonth: "2024-09-01",
    amount: 156.7,
    description: "Entretien chaudière — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.technikabel.name,
    counterpartyAccount: COUNTERPARTIES.technikabel.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2025-03-13",
    accountingMonth: "2025-03-01",
    amount: 198.4,
    description: "Entretien annuel chaudière — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.technikabel.name,
    counterpartyAccount: COUNTERPARTIES.technikabel.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Chaudière",
    transactionDate: "2025-03-25",
    accountingMonth: "2025-03-01",
    amount: 345.0,
    description: "Entretien + nettoyage chaudière centrale — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.climaService.name,
    counterpartyAccount: COUNTERPARTIES.climaService.iban,
    buildingIndex: 4,
  },

  // ── Fire extinguisher maintenance (annual per building) ───────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-02-08",
    accountingMonth: "2023-02-01",
    amount: 312.0,
    description: "Contrôle annuel extincteurs — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-02-22",
    accountingMonth: "2023-02-01",
    amount: 196.0,
    description: "Contrôle annuel extincteurs — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-03-07",
    accountingMonth: "2023-03-01",
    amount: 148.0,
    description: "Contrôle annuel extincteurs — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-03-21",
    accountingMonth: "2023-03-01",
    amount: 98.0,
    description: "Contrôle annuel extincteurs — Le Beffroi",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 3,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-04-04",
    accountingMonth: "2023-04-01",
    amount: 196.0,
    description: "Contrôle annuel extincteurs — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2023-11-15",
    accountingMonth: "2023-11-01",
    amount: 124.0,
    description: "Remplacement extincteur défectueux — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2024-02-07",
    accountingMonth: "2024-02-01",
    amount: 324.0,
    description: "Contrôle annuel extincteurs — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2024-02-21",
    accountingMonth: "2024-02-01",
    amount: 196.0,
    description: "Contrôle annuel extincteurs — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2024-03-06",
    accountingMonth: "2024-03-01",
    amount: 148.0,
    description: "Contrôle annuel extincteurs — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2024-03-20",
    accountingMonth: "2024-03-01",
    amount: 98.0,
    description: "Contrôle annuel extincteurs — Le Beffroi",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 3,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2024-04-03",
    accountingMonth: "2024-04-01",
    amount: 196.0,
    description: "Contrôle annuel extincteurs — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2025-02-06",
    accountingMonth: "2025-02-01",
    amount: 336.0,
    description: "Contrôle annuel extincteurs — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.securitas.name,
    counterpartyAccount: COUNTERPARTIES.securitas.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2025-02-20",
    accountingMonth: "2025-02-01",
    amount: 204.0,
    description: "Contrôle annuel extincteurs — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Extincteurs",
    transactionDate: "2025-03-05",
    accountingMonth: "2025-03-01",
    amount: 154.0,
    description: "Contrôle annuel extincteurs — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.safefire.name,
    counterpartyAccount: COUNTERPARTIES.safefire.iban,
    buildingIndex: 2,
  },

  // ── Cleaning — CleanPro (Bruxelles, monthly) ──────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-01-31",
    accountingMonth: "2023-01-01",
    amount: 320.0,
    description: "Nettoyage parties communes jan 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-02-28",
    accountingMonth: "2023-02-01",
    amount: 320.0,
    description: "Nettoyage parties communes fév 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-03-31",
    accountingMonth: "2023-03-01",
    amount: 320.0,
    description: "Nettoyage parties communes mar 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-04-30",
    accountingMonth: "2023-04-01",
    amount: 320.0,
    description: "Nettoyage parties communes avr 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-05-31",
    accountingMonth: "2023-05-01",
    amount: 320.0,
    description: "Nettoyage parties communes mai 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-06-30",
    accountingMonth: "2023-06-01",
    amount: 320.0,
    description: "Nettoyage parties communes jun 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-07-31",
    accountingMonth: "2023-07-01",
    amount: 320.0,
    description: "Nettoyage parties communes jul 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-08-31",
    accountingMonth: "2023-08-01",
    amount: 320.0,
    description: "Nettoyage parties communes aoû 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-09-30",
    accountingMonth: "2023-09-01",
    amount: 320.0,
    description: "Nettoyage parties communes sep 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-10-31",
    accountingMonth: "2023-10-01",
    amount: 320.0,
    description: "Nettoyage parties communes oct 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-11-30",
    accountingMonth: "2023-11-01",
    amount: 320.0,
    description: "Nettoyage parties communes nov 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-12-31",
    accountingMonth: "2023-12-01",
    amount: 320.0,
    description: "Nettoyage parties communes déc 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-01-31",
    accountingMonth: "2024-01-01",
    amount: 336.0,
    description: "Nettoyage parties communes jan 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-02-29",
    accountingMonth: "2024-02-01",
    amount: 336.0,
    description: "Nettoyage parties communes fév 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-03-31",
    accountingMonth: "2024-03-01",
    amount: 336.0,
    description: "Nettoyage parties communes mar 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-06-30",
    accountingMonth: "2024-06-01",
    amount: 336.0,
    description: "Nettoyage parties communes jun 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-09-30",
    accountingMonth: "2024-09-01",
    amount: 336.0,
    description: "Nettoyage parties communes sep 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-12-31",
    accountingMonth: "2024-12-01",
    amount: 336.0,
    description: "Nettoyage parties communes déc 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2025-01-31",
    accountingMonth: "2025-01-01",
    amount: 352.0,
    description: "Nettoyage parties communes jan 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.cleanPro.name,
    counterpartyAccount: COUNTERPARTIES.cleanPro.iban,
    buildingIndex: 0,
  },

  // ── Cleaning — Sparkle (Liège, quarterly) ─────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-02-28",
    accountingMonth: "2023-02-01",
    amount: 180.0,
    description: "Nettoyage parties communes Q1 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-05-31",
    accountingMonth: "2023-05-01",
    amount: 180.0,
    description: "Nettoyage parties communes Q2 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-08-31",
    accountingMonth: "2023-08-01",
    amount: 180.0,
    description: "Nettoyage parties communes Q3 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2023-11-30",
    accountingMonth: "2023-11-01",
    amount: 180.0,
    description: "Nettoyage parties communes Q4 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-02-29",
    accountingMonth: "2024-02-01",
    amount: 190.0,
    description: "Nettoyage parties communes Q1 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-05-31",
    accountingMonth: "2024-05-01",
    amount: 190.0,
    description: "Nettoyage parties communes Q2 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-08-31",
    accountingMonth: "2024-08-01",
    amount: 190.0,
    description: "Nettoyage parties communes Q3 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2024-11-30",
    accountingMonth: "2024-11-01",
    amount: 190.0,
    description: "Nettoyage parties communes Q4 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Nettoyage communs",
    transactionDate: "2025-02-28",
    accountingMonth: "2025-02-01",
    amount: 200.0,
    description: "Nettoyage parties communes Q1 2025 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.sparkle.name,
    counterpartyAccount: COUNTERPARTIES.sparkle.iban,
    buildingIndex: 1,
  },

  // ── Annuities — Usufruit (Les Tilleuls, quarterly) ────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-01-05",
    accountingMonth: "2023-01-01",
    amount: 750.0,
    description: "Rente usufruit Q1 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-04-05",
    accountingMonth: "2023-04-01",
    amount: 750.0,
    description: "Rente usufruit Q2 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-07-05",
    accountingMonth: "2023-07-01",
    amount: 750.0,
    description: "Rente usufruit Q3 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-10-05",
    accountingMonth: "2023-10-01",
    amount: 750.0,
    description: "Rente usufruit Q4 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-01-05",
    accountingMonth: "2024-01-01",
    amount: 775.0,
    description: "Rente usufruit Q1 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-04-05",
    accountingMonth: "2024-04-01",
    amount: 775.0,
    description: "Rente usufruit Q2 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-07-05",
    accountingMonth: "2024-07-01",
    amount: 775.0,
    description: "Rente usufruit Q3 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-10-05",
    accountingMonth: "2024-10-01",
    amount: 775.0,
    description: "Rente usufruit Q4 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2025-01-05",
    accountingMonth: "2025-01-01",
    amount: 800.0,
    description: "Rente usufruit Q1 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.usufructier1.name,
    counterpartyAccount: COUNTERPARTIES.usufructier1.iban,
    buildingIndex: 0,
  },

  // ── Annuities — Retour notaire (Le Beffroi, annual) ───────────────────────
  {
    direction: "INCOME",
    subcategoryName: "Retour",
    transactionDate: "2023-06-15",
    accountingMonth: "2023-06-01",
    amount: 1200.0,
    description: "Remboursement rente — acte Mercier 2019",
    counterpartyName: COUNTERPARTIES.renteNotaire.name,
    counterpartyAccount: COUNTERPARTIES.renteNotaire.iban,
    buildingIndex: 3,
  },
  {
    direction: "INCOME",
    subcategoryName: "Retour",
    transactionDate: "2024-06-14",
    accountingMonth: "2024-06-01",
    amount: 1200.0,
    description: "Remboursement rente — acte Mercier 2019",
    counterpartyName: COUNTERPARTIES.renteNotaire.name,
    counterpartyAccount: COUNTERPARTIES.renteNotaire.iban,
    buildingIndex: 3,
  },
  {
    direction: "INCOME",
    subcategoryName: "Retour",
    transactionDate: "2025-06-13",
    accountingMonth: "2025-06-01",
    amount: 1200.0,
    description: "Remboursement rente — acte Mercier 2019",
    counterpartyName: COUNTERPARTIES.renteNotaire.name,
    counterpartyAccount: COUNTERPARTIES.renteNotaire.iban,
    buildingIndex: 3,
  },

  // ── Annuities — Usufruit (Résidence Meuse, biannual, different actor) ─────
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-02-01",
    accountingMonth: "2023-02-01",
    amount: 500.0,
    description: "Rente usufruit sem. 1 2023 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.usufructier2.name,
    counterpartyAccount: COUNTERPARTIES.usufructier2.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2023-08-01",
    accountingMonth: "2023-08-01",
    amount: 500.0,
    description: "Rente usufruit sem. 2 2023 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.usufructier2.name,
    counterpartyAccount: COUNTERPARTIES.usufructier2.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-02-01",
    accountingMonth: "2024-02-01",
    amount: 520.0,
    description: "Rente usufruit sem. 1 2024 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.usufructier2.name,
    counterpartyAccount: COUNTERPARTIES.usufructier2.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2024-08-01",
    accountingMonth: "2024-08-01",
    amount: 520.0,
    description: "Rente usufruit sem. 2 2024 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.usufructier2.name,
    counterpartyAccount: COUNTERPARTIES.usufructier2.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Usufruit",
    transactionDate: "2025-02-01",
    accountingMonth: "2025-02-01",
    amount: 540.0,
    description: "Rente usufruit sem. 1 2025 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.usufructier2.name,
    counterpartyAccount: COUNTERPARTIES.usufructier2.iban,
    buildingIndex: 4,
  },

  // ── Property taxes (annual, all buildings) ────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2023-08-31",
    accountingMonth: "2023-08-01",
    amount: 2134.5,
    description: "Précompte immobilier 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2023-09-15",
    accountingMonth: "2023-09-01",
    amount: 1567.8,
    description: "Précompte immobilier 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2023-09-29",
    accountingMonth: "2023-09-01",
    amount: 1123.4,
    description: "Précompte immobilier 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2023-10-06",
    accountingMonth: "2023-10-01",
    amount: 876.2,
    description: "Précompte immobilier 2023 — Le Beffroi",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2023-10-13",
    accountingMonth: "2023-10-01",
    amount: 1432.6,
    description: "Précompte immobilier 2023 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2024-08-30",
    accountingMonth: "2024-08-01",
    amount: 2198.3,
    description: "Précompte immobilier 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2024-09-13",
    accountingMonth: "2024-09-01",
    amount: 1612.4,
    description: "Précompte immobilier 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2024-09-27",
    accountingMonth: "2024-09-01",
    amount: 1156.8,
    description: "Précompte immobilier 2024 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2024-10-04",
    accountingMonth: "2024-10-01",
    amount: 901.3,
    description: "Précompte immobilier 2024 — Le Beffroi",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2024-10-11",
    accountingMonth: "2024-10-01",
    amount: 1478.9,
    description: "Précompte immobilier 2024 — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Précompte immobilier",
    transactionDate: "2025-09-05",
    accountingMonth: "2025-09-01",
    amount: 2265.7,
    description: "Précompte immobilier 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.spfFinances.name,
    counterpartyAccount: COUNTERPARTIES.spfFinances.iban,
  },

  // ── Insurance (annual) ─────────────────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2023-01-10",
    accountingMonth: "2023-01-01",
    amount: 892.4,
    description: "Prime assurance immeuble 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.agInsurance.name,
    counterpartyAccount: COUNTERPARTIES.agInsurance.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2023-01-12",
    accountingMonth: "2023-01-01",
    amount: 634.8,
    description: "Prime assurance immeuble 2023 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.axa.name,
    counterpartyAccount: COUNTERPARTIES.axa.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2023-01-15",
    accountingMonth: "2023-01-01",
    amount: 487.6,
    description: "Prime assurance immeuble 2023 — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.axa.name,
    counterpartyAccount: COUNTERPARTIES.axa.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2024-01-10",
    accountingMonth: "2024-01-01",
    amount: 921.3,
    description: "Prime assurance immeuble 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.agInsurance.name,
    counterpartyAccount: COUNTERPARTIES.agInsurance.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2024-01-12",
    accountingMonth: "2024-01-01",
    amount: 654.2,
    description: "Prime assurance immeuble 2024 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.axa.name,
    counterpartyAccount: COUNTERPARTIES.axa.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2025-01-10",
    accountingMonth: "2025-01-01",
    amount: 948.7,
    description: "Prime assurance immeuble 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.agInsurance.name,
    counterpartyAccount: COUNTERPARTIES.agInsurance.iban,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Assurance habitation",
    transactionDate: "2025-01-12",
    accountingMonth: "2025-01-01",
    amount: 673.9,
    description: "Prime assurance immeuble 2025 — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.axa.name,
    counterpartyAccount: COUNTERPARTIES.axa.iban,
  },

  // ── Plumbing (one-off) ─────────────────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Plomberie",
    transactionDate: "2023-05-18",
    accountingMonth: "2023-05-01",
    amount: 234.6,
    description: "Fuite tuyauterie cave — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.plomberieDupont.name,
    counterpartyAccount: COUNTERPARTIES.plomberieDupont.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Plomberie",
    transactionDate: "2023-10-03",
    accountingMonth: "2023-10-01",
    amount: 189.4,
    description: "Débouchage colonne — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.waterfixBxl.name,
    counterpartyAccount: COUNTERPARTIES.waterfixBxl.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Plomberie",
    transactionDate: "2024-02-19",
    accountingMonth: "2024-02-01",
    amount: 456.8,
    description: "Remplacement compteur eau unité B01 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.plomberieDupont.name,
    counterpartyAccount: COUNTERPARTIES.plomberieDupont.iban,
    buildingIndex: 0,
    unitIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Plomberie",
    transactionDate: "2024-07-08",
    accountingMonth: "2024-07-01",
    amount: 312.5,
    description: "Réparation robinetterie — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.plomberieDupont.name,
    counterpartyAccount: COUNTERPARTIES.plomberieDupont.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Plomberie",
    transactionDate: "2025-01-22",
    accountingMonth: "2025-01-01",
    amount: 278.9,
    description: "Fuite chasse d'eau — Immeuble du Parc unité 02",
    counterpartyName: COUNTERPARTIES.waterfixBxl.name,
    counterpartyAccount: COUNTERPARTIES.waterfixBxl.iban,
    buildingIndex: 1,
    unitIndex: 1,
  },

  // ── Structural works ──────────────────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Structure",
    transactionDate: "2023-06-20",
    accountingMonth: "2023-06-01",
    amount: 3450.0,
    description: "Réfection enduit façade — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.renovImmo.name,
    counterpartyAccount: COUNTERPARTIES.renovImmo.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Toiture",
    transactionDate: "2023-09-05",
    accountingMonth: "2023-09-01",
    amount: 5780.0,
    description: "Réparation toiture — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.toitureWaals.name,
    counterpartyAccount: COUNTERPARTIES.toitureWaals.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Structure",
    transactionDate: "2024-05-14",
    accountingMonth: "2024-05-01",
    amount: 1890.0,
    description: "Remplacement fenêtres parties communes — Le Beffroi",
    counterpartyName: COUNTERPARTIES.vitrage.name,
    buildingIndex: 3,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Toiture",
    transactionDate: "2024-08-22",
    accountingMonth: "2024-08-01",
    amount: 8950.0,
    description: "Réfection complète toiture — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.toitureWaals.name,
    counterpartyAccount: COUNTERPARTIES.toitureWaals.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Structure",
    transactionDate: "2024-11-07",
    accountingMonth: "2024-11-01",
    amount: 2340.0,
    description: "Isolation combles — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.batiTravaux.name,
    counterpartyAccount: COUNTERPARTIES.batiTravaux.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Structure",
    transactionDate: "2025-02-18",
    accountingMonth: "2025-02-01",
    amount: 1240.0,
    description: "Réparation escalier cage B — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.renovImmo.name,
    counterpartyAccount: COUNTERPARTIES.renovImmo.iban,
    buildingIndex: 0,
  },

  // ── Small works (one-off, varied suppliers) ───────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2023-03-28",
    accountingMonth: "2023-03-01",
    amount: 145.0,
    description: "Remplacement serrure entrée — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.locksmith.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2023-07-11",
    accountingMonth: "2023-07-01",
    amount: 289.5,
    description: "Peinture couloir — Immeuble du Parc",
    counterpartyName: COUNTERPARTIES.batiTravaux.name,
    counterpartyAccount: COUNTERPARTIES.batiTravaux.iban,
    buildingIndex: 1,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2023-11-06",
    accountingMonth: "2023-11-01",
    amount: 198.4,
    description: "Réparation interphone — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.elecBxl.name,
    counterpartyAccount: COUNTERPARTIES.elecBxl.iban,
    buildingIndex: 2,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2024-04-23",
    accountingMonth: "2024-04-01",
    amount: 87.6,
    description: "Achat ampoules LED parties communes",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2024-06-17",
    accountingMonth: "2024-06-01",
    amount: 312.8,
    description: "Réparation porte garage — Résidence Meuse",
    counterpartyName: COUNTERPARTIES.batiTravaux.name,
    counterpartyAccount: COUNTERPARTIES.batiTravaux.iban,
    buildingIndex: 4,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2024-09-09",
    accountingMonth: "2024-09-01",
    amount: 156.3,
    description: "Remplacement boîtes aux lettres — Le Beffroi",
    counterpartyName: COUNTERPARTIES.brico.name,
    buildingIndex: 3,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2025-01-14",
    accountingMonth: "2025-01-01",
    amount: 224.7,
    description: "Réparation éclairage extérieur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.elecBxl.name,
    counterpartyAccount: COUNTERPARTIES.elecBxl.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits travaux",
    transactionDate: "2025-03-04",
    accountingMonth: "2025-03-01",
    amount: 178.9,
    description: "Peinture cage d'escalier A — Résidence Gaston",
    counterpartyName: COUNTERPARTIES.batiTravaux.name,
    counterpartyAccount: COUNTERPARTIES.batiTravaux.iban,
    buildingIndex: 2,
  },

  // ── Bank interest income (quarterly) ──────────────────────────────────────
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2023-03-31",
    accountingMonth: "2023-03-01",
    amount: 34.2,
    description: "Intérêts épargne Q1 2023",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2023-06-30",
    accountingMonth: "2023-06-01",
    amount: 41.8,
    description: "Intérêts épargne Q2 2023",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2023-09-30",
    accountingMonth: "2023-09-01",
    amount: 48.6,
    description: "Intérêts épargne Q3 2023",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2023-12-31",
    accountingMonth: "2023-12-01",
    amount: 52.3,
    description: "Intérêts épargne Q4 2023",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2024-03-31",
    accountingMonth: "2024-03-01",
    amount: 67.9,
    description: "Intérêts épargne Q1 2024",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2024-06-30",
    accountingMonth: "2024-06-01",
    amount: 71.4,
    description: "Intérêts épargne Q2 2024",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2024-09-30",
    accountingMonth: "2024-09-01",
    amount: 69.8,
    description: "Intérêts épargne Q3 2024",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2024-12-31",
    accountingMonth: "2024-12-01",
    amount: 74.2,
    description: "Intérêts épargne Q4 2024",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },
  {
    direction: "INCOME",
    subcategoryName: "Banque",
    transactionDate: "2025-03-31",
    accountingMonth: "2025-03-01",
    amount: 78.5,
    description: "Intérêts épargne Q1 2025",
    counterpartyName: COUNTERPARTIES.belfius.name,
    counterpartyAccount: COUNTERPARTIES.belfius.iban,
  },

  // ── Rental deposits (income on entry, expense on return) ──────────────────
  {
    direction: "INCOME",
    subcategoryName: "Garantie locative",
    transactionDate: "2023-01-03",
    accountingMonth: "2023-01-01",
    amount: 1700.0,
    description: "Dépôt garantie locative — Les Tilleuls A01",
    counterpartyName: "Martin Lecomte",
    counterpartyAccount: "BE29001234001001",
    buildingIndex: 0,
    unitIndex: 0,
  },
  {
    direction: "INCOME",
    subcategoryName: "Garantie locative",
    transactionDate: "2023-02-01",
    accountingMonth: "2023-02-01",
    amount: 1560.0,
    description: "Dépôt garantie locative — Immeuble du Parc 01",
    counterpartyName: "Sophie Renard",
    counterpartyAccount: "BE56001234002002",
    buildingIndex: 1,
    unitIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Garantie locative",
    transactionDate: "2023-08-31",
    accountingMonth: "2023-08-01",
    amount: 1560.0,
    description: "Restitution garantie locative — fin bail 01",
    counterpartyName: "Sophie Renard",
    counterpartyAccount: "BE56001234002002",
    buildingIndex: 1,
    unitIndex: 0,
  },
  {
    direction: "INCOME",
    subcategoryName: "Garantie locative",
    transactionDate: "2024-03-01",
    accountingMonth: "2024-03-01",
    amount: 1620.0,
    description: "Dépôt garantie locative — Résidence Gaston 01",
    counterpartyName: "Thomas Van den Berg",
    counterpartyAccount: "BE83001234003003",
    buildingIndex: 2,
    unitIndex: 0,
  },
  {
    direction: "INCOME",
    subcategoryName: "Garantie locative",
    transactionDate: "2024-09-02",
    accountingMonth: "2024-09-01",
    amount: 1780.0,
    description: "Dépôt garantie locative — Les Tilleuls B01",
    counterpartyName: "Nicolas Jacobs",
    counterpartyAccount: "BE41001234004004",
    buildingIndex: 0,
    unitIndex: 2,
  },

  // ── Listing fees (one-off per vacancy) ────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Annonce",
    transactionDate: "2023-01-02",
    accountingMonth: "2023-01-01",
    amount: 89.0,
    description: "Publication annonce Immoweb — Les Tilleuls A01",
    counterpartyName: "Immoweb SA",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Annonce",
    transactionDate: "2023-08-10",
    accountingMonth: "2023-08-01",
    amount: 89.0,
    description: "Publication annonce Immoweb — Immeuble du Parc 01",
    counterpartyName: "Immoweb SA",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Annonce",
    transactionDate: "2024-02-12",
    accountingMonth: "2024-02-01",
    amount: 99.0,
    description: "Publication annonce Immoweb — Résidence Gaston 01",
    counterpartyName: "Immoweb SA",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Annonce",
    transactionDate: "2024-11-05",
    accountingMonth: "2024-11-01",
    amount: 99.0,
    description: "Publication annonce Immoweb — Le Beffroi B",
    counterpartyName: "Immoweb SA",
  },

  // ── State of property inspection ──────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Etat des lieux",
    transactionDate: "2023-01-03",
    accountingMonth: "2023-01-01",
    amount: 275.0,
    description: "État des lieux entrée — Les Tilleuls A01",
    counterpartyName: "Expert Immo Delvaux",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Etat des lieux",
    transactionDate: "2023-09-01",
    accountingMonth: "2023-09-01",
    amount: 275.0,
    description: "État des lieux sortie — Immeuble du Parc 01",
    counterpartyName: "Expert Immo Delvaux",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Etat des lieux",
    transactionDate: "2024-03-01",
    accountingMonth: "2024-03-01",
    amount: 295.0,
    description: "État des lieux entrée — Résidence Gaston 01",
    counterpartyName: "Expert Immo Closset",
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Etat des lieux",
    transactionDate: "2024-09-02",
    accountingMonth: "2024-09-01",
    amount: 295.0,
    description: "État des lieux entrée — Les Tilleuls B01",
    counterpartyName: "Expert Immo Closset",
  },

  // ── Syndic fees (quarterly) ───────────────────────────────────────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2023-01-31",
    accountingMonth: "2023-01-01",
    amount: 120.0,
    description: "Honoraires syndic Q1 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2023-04-30",
    accountingMonth: "2023-04-01",
    amount: 120.0,
    description: "Honoraires syndic Q2 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2023-07-31",
    accountingMonth: "2023-07-01",
    amount: 120.0,
    description: "Honoraires syndic Q3 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2023-10-31",
    accountingMonth: "2023-10-01",
    amount: 120.0,
    description: "Honoraires syndic Q4 2023 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2024-01-31",
    accountingMonth: "2024-01-01",
    amount: 132.0,
    description: "Honoraires syndic Q1 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2024-04-30",
    accountingMonth: "2024-04-01",
    amount: 132.0,
    description: "Honoraires syndic Q2 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2024-07-31",
    accountingMonth: "2024-07-01",
    amount: 132.0,
    description: "Honoraires syndic Q3 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2024-10-31",
    accountingMonth: "2024-10-01",
    amount: 132.0,
    description: "Honoraires syndic Q4 2024 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Petits frais",
    transactionDate: "2025-01-31",
    accountingMonth: "2025-01-01",
    amount: 144.0,
    description: "Honoraires syndic Q1 2025 — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.syndic.name,
    counterpartyAccount: COUNTERPARTIES.syndic.iban,
    buildingIndex: 0,
  },

  // ── Water softener (semi-annual consumable + annual service) ─────────────
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2023-03-20",
    accountingMonth: "2023-03-01",
    amount: 67.4,
    description: "Sel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2023-09-18",
    accountingMonth: "2023-09-01",
    amount: 71.2,
    description: "Sel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2024-03-19",
    accountingMonth: "2024-03-01",
    amount: 74.8,
    description: "Sel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2024-06-12",
    accountingMonth: "2024-06-01",
    amount: 385.0,
    description: "Entretien annuel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.technikabel.name,
    counterpartyAccount: COUNTERPARTIES.technikabel.iban,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2024-09-17",
    accountingMonth: "2024-09-01",
    amount: 74.8,
    description: "Sel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
  {
    direction: "EXPENSE",
    subcategoryName: "Adoucisseur",
    transactionDate: "2025-03-18",
    accountingMonth: "2025-03-01",
    amount: 78.5,
    description: "Sel adoucisseur — Les Tilleuls",
    counterpartyName: COUNTERPARTIES.leroy.name,
    buildingIndex: 0,
  },
];
